dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - tensorFlow
    - opencv
    - opencv-python
    - cv2
    - keras
    - scrapy
    - theano
    - beautifulsoup4
    - request
    - scikit-image
    - mxnet
